### ISSUE TITLE
Initial issues

### ISSUE THREAD

**Issue by andras-tim** [selfish/lovelace-sun-card#3]
Hi,
first, thank you for re-started the project! I checked the forks, and this project looks like the best! :wink:  Because as I see you are thinking in a "product", e.g. you have releases!

However, I have some issues with this fork:
* The font sizes, margins, ... don't fit the other widgets: ![image](https://user-images.githubusercontent.com/619016/226584122-f15d3fbb-3542-49fa-9544-39d6261793df.png)
* The configuration of this widget is different than the README says. (e.g. `timeFormat` => `use12hourClock`, or I can not hide azimuth with `fields: {azimuth: false}`)
* The graphical configuration doesn't generate proper config (e.g. if you switch the language)
* With `darkMode: true` the widget is blank: 
![image](https://user-images.githubusercontent.com/619016/226584821-ab8aaf9b-2910-4da7-a79a-2a7198bbfca9.png)

**Comment by selfish** [comment]
Hey there, thanks for the kind words
I'm so sorry to have never replied to you @andras-tim 
This is very much unlike me, and for some reason, I have just completely missed your issue.

With that said, and assuming you no longer use this anyway, just letting you know I've neglected this project as you see, and I am now going to archive it, because I think https://github.com/rejuvenate/lovelace-horizon-card is a worthy replacement, and this one should be deprecated.

Sorry again for the unfashionably late reply!
